---

- name: Install | Use apt to install Pure-FTPD
  apt: pkg=pure-ftpd state=present
#  when: "ansible_os_family == 'Debian' and 'docker-brain' not in group_names and 'docker-frontend' not in group_names and 'docker-probe' not in group_names"
