---

- set_fact:
    probe_deployment_dir: "{{ probe_project_dir }}/{{ 'current' if irma_deployment_code_version == 'local' else 'releases/' + irma_deployment_release_name }}"

# Install Probe
- include: linux/probe_deployment.yml
  when: ansible_distribution in ['Debian', 'Ubuntu']

- include: windows/probe_deployment.yml
  when: "'Windows' in ansible_distribution"

# Configure (enventually) VirusTotal module
#
# ref: https://github.com/quarkslab/irma-ansible/pull/8
- include: modules_configurations.yml
  when: "'virustotal' in group_names"