---

- name: Common tasks to execute on all servers
  hosts: all
  sudo: yes
  roles:
    - { role: quarkslab.apt, tags: 'apt' }
    - { role: franklinkim.ufw, tags: 'ufw', when: "'docker-brain' not in group_names and 'docker-frontend' not in group_names and 'docker-probe' not in group_names"}
    - { role: quarkslab.irma_provisioning_common, tags: 'common' }
    - { role: mivok0.users, tags: 'users' }
    - { role: franklinkim.sudo, tags: 'sudo' }
    - { role: ANXS.openssh, tags: 'openssh' }

- name: Frontend provisioning
  hosts: ["frontend", "frontend-demo"]
  sudo: yes
  roles:
    - { role: quarkslab.nodejs, tags: 'nodejs' }
    - { role: gdamjan.uwsgi, tags: 'uwsgi' }
    - { role: Stouts.mongodb, tags: 'mongodb' }
    - { role: ANXS.postgresql, tags: 'postgresql' }
    - { role: quarkslab.supervisor, tags: 'supervisor', supervisor_programs: "{{ supervisor_programs_frontend }}" }
    - { role: quarkslab.irma_provisioning_frontend, tags: 'frontend' }
    - { role: jdauphant.nginx, tags: 'nginx' }
    - { role: quarkslab.ufw_additional, tags: 'ufw', ufw_additional_rules: "{{ frontend_ufw_additional_rules }}", when: "'docker-brain' not in group_names and 'docker-frontend' not in group_names and 'docker-probe' not in group_names" }


- name: Brain provisioning
  hosts: brain
  sudo: yes
  roles:
    - { role: quarkslab.supervisor, tags: 'supervisor', supervisor_programs: "{{ supervisor_programs_brain }}" }
    - { role: Mayeu.RabbitMQ, tags: 'rabbitmq' }
    - { role: quarkslab.pureftpd, tags: 'pureftpd' }
    - { role: quarkslab.irma_provisioning_brain, tags: 'brain' }
    - { role: quarkslab.ufw_additional, tags: 'ufw', ufw_additional_rules: "{{ brain_ufw_additional_rules }}", when: "'docker-brain' not in group_names and 'docker-frontend' not in group_names and 'docker-probe' not in group_names" }


- name: Probe provisioning
  hosts: probe
  sudo: yes
  roles:
    - { role: quarkslab.irma_provisioning_probe, tags: 'probe' }
    - { role: quarkslab.supervisor, tags: 'supervisor', supervisor_programs: "{{ supervisor_programs_probe }}" }

- name: Probe provisioning
  hosts: docker-probe
  sudo: yes
  roles:
    - { role: quarkslab.irma_provisioning_probe, tags: 'probe' }
    - { role: quarkslab.supervisor, tags: 'supervisor', supervisor_programs: "{{ supervisor_programs_probe }}" }


# Antivirus section
- name: ClamAV provisioning
  hosts: clamav
  sudo: yes
  roles:
    - { role: quarkslab.clamav, tags: 'clamav' }

- name: ComodoCAVL provisioning
  hosts: comodo
  sudo: yes
  roles:
    - { role: quarkslab.comodo_cavl, tags: 'comodo' }

- name: McAfee VSCL provisioning
  hosts: mcafee
  sudo: yes
  roles:
    - { role: quarkslab.mcafee_vscl, tags: 'mcafee_vscl' }

- name: StaticAnalyzer provisioning
  hosts: static-analyzer
  sudo: yes
  roles:
    - { role: quarkslab.static_analyzer, tags: 'static-analyzer' }

- name: VirusTotal provisioning
  hosts: virustotal
  sudo: yes
  roles:
    - { role: quarkslab.virustotal, tags: 'virustotal' }

- name: AVG provisioning
  hosts: avg
  roles:
    - { role: quarkslab.avg, tags: 'avg' }

- name: AVG provisioning
  hosts: bitdefender
  roles:
    - { role: quarkslab.bitdefender, tags: 'bitdefender' }

- name: EScan provisioning
  hosts: escan
  roles:
    - { role: quarkslab.escan, tags: 'escan' }

- name: VirusBlokAda
  hosts: virusblokada
  roles:
    - { role: quarkslab.virusblokada , tags: 'virusblokada' }

- name: Zoner provisioning
  hosts: zoner
  roles:
    - { role: quarkslab.zoner, tags: 'zoner' }

- name: DrWeb provisioning
  hosts: drweb
  roles:
    - { role: quarkslab.drweb, tags: 'drweb' }

- name: Avast provisioning
  hosts: avast
  roles:
    - { role: quarkslab.avast, tags: 'avast' }

- name: FSecure provisioning
  hosts: fsecure
  roles:
    - { role: quarkslab.fsecure, tags: 'fsecure' }

- name: PEiD provisioning
  hosts: peid
  sudo: yes
  roles:
    - { role: quarkslab.peid, tags: 'peid' }


# vim: sw=2
